version: '3.8'
services:
  node-app:
    build: .
    ports:
      - '8080:8080'
    environment:
      - PORT=8080
      - DATABASE_URL=postgresql://postgres:ghandor@postgres:5432/library
      - JWT_SECRET=BurganSecretKey
      - TMDB_BASE_URL=https://api.themoviedb.org/3
      - API_KEY=cbf8c8b92d763006fd1a5ee482437b27
      - REDIS_HOST=redis
      
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: burgan
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ghandor
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - '6379:6379'

volumes:
  pgdata:
